import { describe, it, expect } from "vitest";
import type { TaskIssue, DiscordEmbed, DiscordPayload } from "../types.js";
import { truncateTitle, formatIssueLink, escapeMarkdownBrackets } from "../types.js";

describe("types", () => {
  it("TaskIssue can be constructed with valid data", () => {
    const issue: TaskIssue = {
      id: "abc-123",
      identifier: "PERS-42",
      title: "Fix login bug",
      status: "In Progress",
      statusType: "started",
      priority: 2,
      dueDate: "2026-03-01",
      updatedAt: "2026-03-01T10:00:00.000Z",
      teamName: "Personal",
      teamKey: "PERS",
      labels: ["work"],
      url: "https://linear.app/workspace/issue/PERS-42",
      source: "personal",
      milestone: null,
      assignee: null,
    };

    expect(issue.id).toBe("abc-123");
    expect(issue.identifier).toBe("PERS-42");
    expect(issue.source).toBe("personal");
    expect(issue.labels).toEqual(["work"]);
  });

  it("TaskIssue accepts null dueDate", () => {
    const issue: TaskIssue = {
      id: "def-456",
      identifier: "PERS-15",
      title: "Buy groceries",
      status: "Todo",
      statusType: "unstarted",
      priority: 4,
      dueDate: null,
      updatedAt: "2026-02-23T09:00:00.000Z",
      teamName: "Personal",
      teamKey: "PERS",
      labels: ["private"],
      url: "https://linear.app/workspace/issue/PERS-15",
      source: "personal",
      milestone: null,
      assignee: null,
    };

    expect(issue.dueDate).toBeNull();
  });

  it("TaskIssue accepts company source", () => {
    const issue: TaskIssue = {
      id: "ghi-789",
      identifier: "ENG-100",
      title: "Company task",
      status: "Wait",
      statusType: "started",
      priority: 1,
      dueDate: "2026-02-28",
      updatedAt: "2026-02-28T10:00:00.000Z",
      teamName: "Engineering",
      teamKey: "ENG",
      labels: [],
      url: "https://linear.app/company/issue/ENG-100",
      source: "company",
      milestone: null,
      assignee: null,
    };

    expect(issue.source).toBe("company");
  });

  it("DiscordEmbed can be constructed with all optional fields", () => {
    const embed: DiscordEmbed = {
      title: "Daily Summary",
      description: "Here are your tasks",
      color: 0x5865f2,
      fields: [
        { name: "Task 1", value: "Do something", inline: true },
        { name: "Task 2", value: "Do another thing" },
      ],
      footer: { text: "Generated by task-system" },
      timestamp: "2026-02-23T09:00:00Z",
    };

    expect(embed.title).toBe("Daily Summary");
    expect(embed.fields).toHaveLength(2);
  });

  it("DiscordEmbed can be constructed with no fields", () => {
    const embed: DiscordEmbed = {};
    expect(embed.title).toBeUndefined();
  });

  it("DiscordPayload can be constructed", () => {
    const payload: DiscordPayload = {
      content: "Hello",
      username: "Task Bot",
      embeds: [{ title: "Test" }],
    };

    expect(payload.content).toBe("Hello");
    expect(payload.embeds).toHaveLength(1);
  });
});

describe("truncateTitle", () => {
  it("returns title as-is when within limit", () => {
    expect(truncateTitle("Short title")).toBe("Short title");
  });

  it("returns title as-is when exactly at limit", () => {
    const title = "a".repeat(50);
    expect(truncateTitle(title)).toBe(title);
  });

  it("truncates and adds ellipsis when over limit", () => {
    const title = "a".repeat(60);
    expect(truncateTitle(title)).toBe("a".repeat(50) + "…");
  });

  it("supports custom max length", () => {
    expect(truncateTitle("Hello, World!", 5)).toBe("Hello…");
  });
});

describe("formatIssueLink", () => {
  it("returns markdown link with identifier and url", () => {
    const issue: TaskIssue = {
      id: "test",
      identifier: "ENG-123",
      title: "Test",
      status: "Todo",
      statusType: "unstarted",
      priority: 3,
      dueDate: null,
      updatedAt: "2026-02-23T09:00:00.000Z",
      teamName: "Engineering",
      teamKey: "ENG",
      labels: [],
      url: "https://linear.app/company/issue/ENG-123",
      source: "company",
      milestone: null,
      assignee: null,
    };
    expect(formatIssueLink(issue)).toBe("[ENG-123](https://linear.app/company/issue/ENG-123)");
  });
});

describe("escapeMarkdownBrackets", () => {
  it("escapes [ and ] in text", () => {
    expect(escapeMarkdownBrackets("[Bug] Fix login")).toBe("\\[Bug\\] Fix login");
  });

  it("returns text unchanged when no brackets", () => {
    expect(escapeMarkdownBrackets("Normal title")).toBe("Normal title");
  });

  it("escapes multiple brackets", () => {
    expect(escapeMarkdownBrackets("[a][b]")).toBe("\\[a\\]\\[b\\]");
  });

  it("handles empty string", () => {
    expect(escapeMarkdownBrackets("")).toBe("");
  });
});
